export const AUTH_AUTH = 'AUTH_AUTH';
export const AUTH_AUTH_SUCCESS = 'AUTH_AUTH_SUCCESS';
export const AUTH_AUTH_FAILURE = 'AUTH_AUTH_FAIlURE';

export const AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAILURE = 'USER_CHANGE_PASSWORD_FAILURE';

export const HIERARCHY_GET_HIERARCHY = 'HIERARCHY_GET_HIERARCHY';
export const HIERARCHY_GET_HIERARCHY_SUCCESS = 'HIERARCHY_GET_HIERARCHY_SUCCESS';
export const HIERARCHY_GET_HIERARCHY_FAILURE = 'HIERARCHY_GET_HIERARCHY_FAILURE';

export const HIERARCHY_GET_HIERARCHY_NODE = 'HIERARCHY_GET_HIERARCHY_NODE';
export const HIERARCHY_GET_HIERARCHY_NODE_SUCCESS = 'HIERARCHY_GET_HIERARCHY_NODE_SUCCESS';
export const HIERARCHY_GET_HIERARCHY_NODE_FAILURE = 'HIERARCHY_GET_HIERARCHY_NODE_FAILURE';

export const HIERARCHY_CREATE_HIERARCHY_NODE = 'HIERARCHY_CREATE_HIERARCHY_NODE';
export const HIERARCHY_CREATE_HIERARCHY_NODE_SUCCESS = 'HIERARCHY_CREATE_HIERARCHY_NODE_SUCCESS';
export const HIERARCHY_CREATE_HIERARCHY_NODE_FAILURE = 'HIERARCHY_CREATE_HIERARCHY_NODE_FAILURE';

export const HIERARCHY_DELETE_HIERARCHY_NODE = 'HIERARCHY_DELETE_HIERARCHY_NODE';
export const HIERARCHY_DELETE_HIERARCHY_NODE_SUCCESS = 'HIERARCHY_DELETE_HIERARCHY_NODE_SUCCESS';
export const HIERARCHY_DELETE_HIERARCHY_NODE_FAILURE = 'HIERARCHY_DELETE_HIERARCHY_NODE_FAILURE';

export const HIERARCHY_EDIT_HIERARCHY_NODE = 'HIERARCHY_EDIT_HIERARCHY_NODE';

